In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("car_evaluation.csv")

In [3]:
df.head()

   vhigh vhigh.1  2 2.1  small   low  unacc
0  vhigh   vhigh  2   2  small   med  unacc
1  vhigh   vhigh  2   2  small  high  unacc
2  vhigh   vhigh  2   2    med   low  unacc
3  vhigh   vhigh  2   2    med   med  unacc
4  vhigh   vhigh  2   2    med  high  unacc

In [4]:
df.isnull().sum()

vhigh      0
vhigh.1    0
2          0
2.1        0
small      0
low        0
unacc      0
dtype: int64

In [5]:
df.shape

(1727, 7)

In [6]:
column_names = ["Buying","maint","doors","persons","lug_boot","safety","class"]

In [7]:
df.columns = column_names

In [8]:
df.head()

  Buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    med  unacc
1  vhigh  vhigh     2       2    small   high  unacc
2  vhigh  vhigh     2       2      med    low  unacc
3  vhigh  vhigh     2       2      med    med  unacc
4  vhigh  vhigh     2       2      med   high  unacc

In [9]:
df.dtypes

Buying      str
maint       str
doors       str
persons     str
lug_boot    str
safety      str
class       str
dtype: object

In [11]:
df["Buying"].unique()

<StringArray>
['vhigh', 'high', 'med', 'low']
Length: 4, dtype: str

In [12]:
df["maint"].unique()

<StringArray>
['vhigh', 'high', 'med', 'low']
Length: 4, dtype: str

In [13]:
df["doors"].unique()

<StringArray>
['2', '3', '4', '5more']
Length: 4, dtype: str

In [14]:
df["doors"] = df["doors"].replace("5more","5")

In [15]:
df["doors"].unique()

<StringArray>
['2', '3', '4', '5']
Length: 4, dtype: str

In [16]:
df["persons"].unique()

<StringArray>
['2', '4', 'more']
Length: 3, dtype: str

In [17]:
df["persons"] = df["persons"].replace("more","5")

In [18]:
df["persons"].unique()

<StringArray>
['2', '4', '5']
Length: 3, dtype: str

In [19]:
df["doors"] = df["doors"].astype(int)

In [20]:
df["persons"] = df["persons"].astype(int)

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1727 entries, 0 to 1726
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Buying    1727 non-null   str
 1   maint     1727 non-null   str
 2   doors     1727 non-null   int64
 3   persons   1727 non-null   int64
 4   lug_boot  1727 non-null   str
 5   safety    1727 non-null   str
 6   class     1727 non-null   str
dtypes: int64(2), str(5)
memory usage: 94.6 KB

In [22]:
X = df.drop("class" , axis = 1)
y = df["class"]

In [23]:
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size = 0.25 , random_state = 42)

In [24]:
from sklearn.preprocessing import OrdinalEncoder

In [25]:
df.columns

Index(['Buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class'], dtype='str')

In [26]:
categoricall_cols = ["Buying" , "maint" , "lug_boot" , "safety"]

In [29]:
df["safety"].value_counts()

safety
med     576
high    576
low     575
Name: count, dtype: int64

In [27]:
numerical_cols = ["doors" , "persons"]

In [28]:
ordinal_encoder = OrdinalEncoder(categories=[
    ["low","med","high","vhigh"],
    ["low","med","high","vhigh"],
    ["small","med","big"],
    ["low","med","high"]
])

In [30]:
X_train[categoricall_cols] = ordinal_encoder.fit_transform(X_train[categoricall_cols])

In [31]:
X_test[categoricall_cols] = ordinal_encoder.transform(X_test[categoricall_cols])

In [32]:
X_test

      Buying  maint  doors  persons  lug_boot  safety
599      2.0    2.0      4        2       2.0     0.0
932      1.0    3.0      4        4       2.0     0.0
628      2.0    2.0      5        2       2.0     2.0
1497     0.0    2.0      5        4       1.0     1.0
1262     1.0    0.0      4        5       1.0     0.0
...      ...    ...    ...      ...       ...     ...
1368     0.0    3.0      4        5       0.0     1.0
619      2.0    2.0      4        5       2.0     2.0
1512     0.0    1.0      2        2       0.0     1.0
1234     1.0    0.0      3        5       0.0     2.0
538      2.0    3.0      5        5       2.0     2.0

[432 rows x 6 columns]

In [33]:
X_train

      Buying  maint  doors  persons  lug_boot  safety
1412     0.0    2.0      2        4       0.0     0.0
756      2.0    0.0      2        2       0.0     1.0
589      2.0    2.0      3        5       1.0     2.0
906      1.0    3.0      3        4       2.0     1.0
1022     1.0    2.0      3        5       2.0     0.0
...      ...    ...    ...      ...       ...     ...
1130     1.0    1.0      3        5       2.0     0.0
1294     1.0    0.0      5        5       2.0     2.0
860      2.0    0.0      5        5       2.0     0.0
1459     0.0    2.0      4        2       0.0     2.0
1126     1.0    1.0      3        5       0.0     2.0

[1295 rows x 6 columns]

In [34]:
from sklearn.metrics import classification_report , confusion_matrix , accuracy_score

In [35]:
from sklearn.tree import DecisionTreeClassifier

In [36]:
model = DecisionTreeClassifier()

In [37]:
from sklearn.model_selection import GridSearchCV

In [38]:
param_grid = {
    "criterion": ["gini" , "entropy" , "log_loss"],
    "splitter" : ["best","random"],
    "max_features" : ["auto","sqrt","log2"]
}

In [39]:
grid = GridSearchCV(estimator=model , param_grid = param_grid , n_jobs = -1 , scoring = "accuracy")

In [40]:
grid.fit(X_train,y_train)

c:\Users\Casper\OneDrive\Desktop\Machine_Learning\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:490: FitFailedWarning:
30 fits failed out of a total of 90.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
13 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\Casper\OneDrive\Desktop\Machine_Learning\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Casper\OneDrive\Desktop\Machine_Learning\.venv\Lib\site-packages\sklearn\base.py", line 1329, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\Users\Casper\OneDrive\Desktop\Machine_Learning\.venv\Lib\site-packages\sklearn\base.py", line 492, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\Casper\OneDrive\Desktop\Machine_Learning\.venv\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
17 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\Casper\OneDrive\Desktop\Machine_Learning\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Casper\OneDrive\Desktop\Machine_Learning\.venv\Lib\site-packages\sklearn\base.py", line 1329, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\Users\Casper\OneDrive\Desktop\Machine_Learning\.venv\Lib\site-packages\sklearn\base.py", line 492, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\Casper\OneDrive\Desktop\Machine_Learning\.venv\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
c:\Users\Casper\OneDrive\Desktop\Machine_Learning\.venv\Lib\site-packages\sklearn\model_selection\_search.py:1137: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.91428571 0.87258687 0.9027027  0.89420849
        nan        nan 0.89498069 0.89498069 0.92277992 0.87799228
        nan        nan 0.92664093 0.89420849 0.92046332 0.87258687]
  warnings.warn(

GridSearchCV(estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             scoring='accuracy')

In [41]:
y_pred = grid.predict(X_test)

In [42]:
accuracy_score(y_test,y_pred)

0.9398148148148148